### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by bernardesrodrigo** [PatrickMcvay/UWPModbus#1]
Hi,
Do you have a manual or help file about how to use the dll?

**Comment by satish-basa** [comment]
HI,
Good job, Please share manual or a snippet for using it.

**Comment by PatrickMcvay** [comment]
I will have a sample application up soon. Sorry, I have been extremely busy and this just got pushed to the side.

**Comment by PatrickMcvay** [comment]
You can find the sample app here [https://github.com/PatrickMcvay/UWPModbusSampleApp](https://github.com/PatrickMcvay/UWPModbusSampleApp) . It has not been tested yet, but it should work (might have a few bugs) good enough to give you a general idea of how to use the library.

**Comment by PatrickMcvay** [comment]
Let me know if this helped and I will close the issue. Thanks.

**Comment by bernardesrodrigo** [comment]
Hi Patrick, I´m sorry for the delay. In that time I moved to python with pymodbus and could implement the app in an easier way. Thanks a lot.
