### ISSUE TITLE
NuGet Install Failed

### ISSUE THREAD

**Issue by salinaspaul** [PatrickMcvay/UWPModbus#2]
Hello!

I tried to install this via NuGet on VS2017, but I get the following output and error:

 GET https://api.nuget.org/v3-flatcontainer/uwpmodbus.utilities/index.json
  NotFound https://api.nuget.org/v3-flatcontainer/uwpmodbus.utilities/index.json 248ms
NU1101: Unable to find package UWPModbus.Utilities. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

**Comment by PatrickMcvay** [comment]
I do apologize for that. Apparently I forgot to upload that project. It is in the process of being validated. It is saying that could take up to an hour to complete.

**Comment by PatrickMcvay** [comment]
It should be good to download now.

**Comment by PatrickMcvay** [comment]
Let me know if this fixed your issue so I can close the issue. Thanks.

**Comment by salinaspaul** [comment]
OK, I will try in a day or two.

- Paul Salinas
